#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

source $OPENSHIFT_CARTRIDGE_SDK_BASH


PGPASSWORD=$OPENSHIFT_POSTGRESQL_DB_PASSWORD
dbname=acmeairdatabase

if [[ `psql -tAc "SELECT 1 FROM pg_database WHERE datname='$dbname'"` != "1" ]]
then
  createdb $dbname -h $OPENSHIFT_POSTGRESQL_DB_HOST -p $OPENSHIFT_POSTGRESQL_DB_PORT -U $OPENSHIFT_POSTGRESQL_DB_USERNAME
  fi
